# Form implementation generated from reading ui file 'e:\Software Development\nwb scheduler\desktop_client\home.ui'
#
# Created by: PyQt6 UI code generator 6.3.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(925, 625)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.navbar_frame = QtWidgets.QFrame(self.frame)
        self.navbar_frame.setMinimumSize(QtCore.QSize(100, 0))
        self.navbar_frame.setMaximumSize(QtCore.QSize(350, 16777215))
        self.navbar_frame.setStyleSheet("#navbar_frame {\n"
"background-color: #24A19C;\n"
"}\n"
"\n"
"QPushButton {\n"
"border: none;\n"
"font-size: 20px;\n"
"color: #F0F0F0;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: rgba(228, 228, 228, 0.28);\n"
"}")
        self.navbar_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.navbar_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.navbar_frame.setObjectName("navbar_frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.navbar_frame)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_3 = QtWidgets.QFrame(self.navbar_frame)
        self.frame_3.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_2.addWidget(self.frame_3)
        self.label = QtWidgets.QLabel(self.navbar_frame)
        self.label.setMaximumSize(QtCore.QSize(16777215, 50))
        self.label.setStyleSheet("font-size: 25px;\n"
"color: rgb(255, 255, 255);\n"
"font-weight: bold;")
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.home_button = QtWidgets.QPushButton(self.navbar_frame)
        self.home_button.setMinimumSize(QtCore.QSize(0, 50))
        self.home_button.setObjectName("home_button")
        self.verticalLayout_2.addWidget(self.home_button)
        self.congregation_button = QtWidgets.QPushButton(self.navbar_frame)
        self.congregation_button.setMinimumSize(QtCore.QSize(0, 50))
        self.congregation_button.setObjectName("congregation_button")
        self.verticalLayout_2.addWidget(self.congregation_button)
        self.scheduler_button = QtWidgets.QPushButton(self.navbar_frame)
        self.scheduler_button.setMinimumSize(QtCore.QSize(0, 50))
        self.scheduler_button.setObjectName("scheduler_button")
        self.verticalLayout_2.addWidget(self.scheduler_button)
        self.reports_button = QtWidgets.QPushButton(self.navbar_frame)
        self.reports_button.setMinimumSize(QtCore.QSize(0, 50))
        self.reports_button.setObjectName("reports_button")
        self.verticalLayout_2.addWidget(self.reports_button)
        self.frame_2 = QtWidgets.QFrame(self.navbar_frame)
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_2.addWidget(self.frame_2)
        self.horizontalLayout.addWidget(self.navbar_frame)
        self.main_frame = QtWidgets.QFrame(self.frame)
        self.main_frame.setStyleSheet("background-color: #F0F0F0;")
        self.main_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.main_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.main_frame.setObjectName("main_frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.main_frame)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.clone_widget = QtWidgets.QWidget(self.main_frame)
        self.clone_widget.setObjectName("clone_widget")
        self.verticalLayout_3.addWidget(self.clone_widget)
        self.horizontalLayout.addWidget(self.main_frame)
        self.verticalLayout.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 925, 21))
        self.menubar.setObjectName("menubar")
        self.menuAbout = QtWidgets.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        self.menuAbout_2 = QtWidgets.QMenu(self.menubar)
        self.menuAbout_2.setObjectName("menuAbout_2")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.actionApperance = QtGui.QAction(MainWindow)
        self.actionApperance.setObjectName("actionApperance")
        self.actionTerms_and_Conditions = QtGui.QAction(MainWindow)
        self.actionTerms_and_Conditions.setObjectName("actionTerms_and_Conditions")
        self.actionContact_Me = QtGui.QAction(MainWindow)
        self.actionContact_Me.setObjectName("actionContact_Me")
        self.actionCheck_For_Updates = QtGui.QAction(MainWindow)
        self.actionCheck_For_Updates.setObjectName("actionCheck_For_Updates")
        self.menuAbout.addAction(self.actionApperance)
        self.menuAbout.addAction(self.actionCheck_For_Updates)
        self.menuAbout_2.addAction(self.actionTerms_and_Conditions)
        self.menuHelp.addAction(self.actionContact_Me)
        self.menubar.addAction(self.menuAbout.menuAction())
        self.menubar.addAction(self.menuAbout_2.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "NWB SCHEDULER MENU"))
        self.home_button.setText(_translate("MainWindow", "Home"))
        self.congregation_button.setText(_translate("MainWindow", "Congregation"))
        self.scheduler_button.setText(_translate("MainWindow", "Scheduler"))
        self.reports_button.setText(_translate("MainWindow", "Reports"))
        self.menuAbout.setTitle(_translate("MainWindow", "Options"))
        self.menuAbout_2.setTitle(_translate("MainWindow", "About"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionApperance.setText(_translate("MainWindow", "Apperance "))
        self.actionTerms_and_Conditions.setText(_translate("MainWindow", "Terms and Conditions"))
        self.actionContact_Me.setText(_translate("MainWindow", "Contact Me"))
        self.actionCheck_For_Updates.setText(_translate("MainWindow", "Check For Updates"))
